# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Lab and PoCs(ccbc54ce-61f8-463d-b05f-a05d625c3567)'
    subscriptionId: 'ccbc54ce-61f8-463d-b05f-a05d625c3567'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rot-poc2'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/Cloud/IaC/main.bicep'
    overrideParameters: '-secretKey $(SECRET_KEY) -azureClientSecret $(AZURE_CLIENT_SECRET) -azureTenantId $(AZURE_TENANT_ID)  -azureClientId $(AZURE_CLIENT_ID) -contributorPrincipalIds $(CONTRIBUTOR_PRINCIPAL_IDS)'
    deploymentMode: 'Incremental'
