[package]
name = "rot-fe"
version = "0.1.0"
edition = "2024"

[dependencies]
components = "0.1.0"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }
